Portfolio mobile final Version
mrkamin/Portfolio-finish-mobile-version pull request #1
Opened 2022-09-23 08:05 UTC by mrkamin

Pull Request for my Portfolio Mobile Final Version

2022-09-23 08:55 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @mrkamin  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Great work using the same font as Figma design ☑️ 
- Commits are descriptive and meaningful :+1: 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-23 08:55 UTC, Nyame-Wolf commented on index.html
> +            <p class="Lets-Connect-Statement">Let Connect</p>
Kindly note that this is a `<hx>` e.g `<h3>` not a `<p>` tag. It is important to use the correct tags for your project for screen readers to be able to figure out the semantics.

2022-09-23 08:55 UTC, Nyame-Wolf commented on index.html
> +                                    <a href="#">Javascript</a>
Kindly note the the images don't show. 
<img width="599" alt="Screenshot 2022-09-23 at 11 31 07" src="https://user-images.githubusercontent.com/48546992/191921807-bd0bbc05-662c-4ff9-aba7-124b0870cae3.png">

This may be because the path to the images is broken. Please fix the path so that they can display

2022-09-23 08:55 UTC, Nyame-Wolf commented on index.html
> +                                <i class="Fa Fa-angellist"></i>
Kindly note that the social media icons on your page do not show. Please fix this.

- [ ] This is your design
<img width="599" alt="Screenshot 2022-09-23 at 11 31 07" src="https://user-images.githubusercontent.com/48546992/191923266-e1e616db-08a4-4a5f-a0d8-c5b00734056c.png">


- [ ] This is the figma design

<img width="1206" alt="Screenshot 2022-09-23 at 11 37 53" src="https://user-images.githubusercontent.com/48546992/191923062-f32cce4e-f830-425e-a577-3f709e11208c.png">

2022-09-23 08:55 UTC, Nyame-Wolf commented on README.md
> +This project is [MIT](./LICENSE) licensed.
[OPTIONAL] I recommend you add an MIT.md file for the licence. Instructions on how to add this is at the bottom of the [readmeTemplate](https://github.com/microverseinc/readme-template/blob/master/README.md) you used when setting up your readme

You can also use[MIT,md template](https://choosealicense.com/licenses/mit/) here.

2022-09-23 08:55 UTC, Nyame-Wolf commented on index.html
> +              <button type="button" class="Bar">
Kindly note that this navbar is not visible on your page. Please fix this
<img width="607" alt="Screenshot 2022-09-23 at 11 48 40" src="https://user-images.githubusercontent.com/48546992/191924912-f42fb1cd-6e09-4537-ab11-0276671f42b3.png">

Also note that the social media icons are not visible. Please fix this

2022-09-23 08:55 UTC, Nyame-Wolf commented on index.html
> +      </section>
Kindly note that your form does not match figmas design padding and margin
Also note that the textarea has a width and padding as well

- [ ] This is your design
<img width="622" alt="Screenshot 2022-09-23 at 11 51 46" src="https://user-images.githubusercontent.com/48546992/191925606-bdee7986-4aaf-4a87-a576-3b1cef1e0d57.png">

- [ ]  This is the template 
- [ ] 
<img width="1200" alt="Screenshot 2022-09-23 at 11 51 34" src="https://user-images.githubusercontent.com/48546992/191925648-d16a48e0-3515-44ff-87b2-251e2b1027d9.png">

2022-09-23 13:47 UTC, Tadesse-Alemayehu approved these changes
Hi @mrkamin 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approve_happy](https://user-images.githubusercontent.com/69077061/191975050-e27fa5a7-20fe-4469-801c-5a99c5080eba.gif)


## Highlights
- Changes from the previous code reviewer have been implemented well :+1: .

## Optional suggestions
- Your commit messages were sweet, but to improve that even more, You don't necessarily have to add a `commit` word in your commits, you should rather mention what you did. something like `Fix something` or `Update something`

- Also it seems you have a conflict in your branch. make sure to fix that.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 07:33 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @mrkamin 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 15:17 UTC, closed without merging